 import { type Metadata } from "next";
import "@/styles/globals.css";
import { Playfair_Display, Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import SmoothScroll from "@/LinesScroll";
import CustomScrollbar from "@/CustomScrollbar";
import GridOverlay from "@/GridOverlay";
import Header from "@/layout/Header/Header";
import Footer from "@/layout/Header/footer/footer";
import { WishlistProvider, CartProvider } from "@/sections/cart.tsx/cart";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" dir="ltr" className={`${playfairDisplay.variable} ${inter.variable}`}>
      <body className="font-[family-name:var(--font-inter)]">
        <TRPCReactProvider>
          <WishlistProvider>
            <CartProvider>
              <Header />
              <SmoothScroll>
                {children}
              </SmoothScroll>
              <Footer />
            </CartProvider>
          </WishlistProvider>
        </TRPCReactProvider>
        <CustomScrollbar />
        <GridOverlay />
      </body>
    </html>
  );
}